// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnboardingCS.Models;

namespace OnboardingCS.Migrations
{
    [DbContext(typeof(HanOnboardingSkdDbContext))]
    [Migration("20210715041308_add label model")]
    partial class addlabelmodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnboardingCS.Models.Label", b =>
                {
                    b.Property<int>("labelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("labelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("labelId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("OnboardingCS.Models.TodoItem", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("labelId")
                        .HasColumnType("int");

                    b.Property<bool>("TodoIsDone")
                        .HasColumnType("bit");

                    b.Property<string>("TodoName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TodoId");

                    b.HasIndex("labelId");

                    b.ToTable("TodoItem");
                });

            modelBuilder.Entity("OnboardingCS.Models.TodoItem", b =>
                {
                    b.HasOne("OnboardingCS.Models.Label", null)
                        .WithMany("todos")
                        .HasForeignKey("labelId");
                });

            modelBuilder.Entity("OnboardingCS.Models.Label", b =>
                {
                    b.Navigation("todos");
                });
#pragma warning restore 612, 618
        }
    }
}
